baud_rate: 9600
devices:
- device_id: 15039823
  enumerator: 17
  name: Rolladen Buero
  paired: true
- device_id: 5363007
  enumerator: 9
  name: null
  paired: false
- device_id: 3365892
  enumerator: 15
  name: null
  paired: false
- device_id: 6618678
  enumerator: 11
  name: null
  paired: false
- device_id: 16656029
  enumerator: 11
  name: null
  paired: false
- device_id: 8425402
  enumerator: 18
  name: Schlafzimmer Mitte
  paired: false
- device_id: 10652940
  enumerator: 18
  name: Wohnzimmer Fenster
  paired: false
- device_id: 15351263
  enumerator: 18
  name: Wohnzimmer Tuer
  paired: false
- device_id: 4084179
  enumerator: 9
  name: null
  paired: false
serial_port: COM3
timeout: 10
